### ISSUE TITLE
Is doing this will work in app direectory router handlers?

### ISSUE THREAD

**Issue by DannyPark1** [maximilianschmitt/next-auth#8]
would this whole thing also work via app directory route handlers?? or should it be done only via pages api route handler?

**Comment by maximilianschmitt** [comment]
Hi @DannyPark1! Right now it only works for the pages directory. Will look into making it available to the app directory when it's a bit more stable :)

**Comment by DannyPark1** [comment]
@maximilianschmitt Max ur article helped me alot setting the proxy thank you. Tho i have a question, is there a possible way to forward a incoming request to another request? Here is the scenario
- user request a /profile API
- at proxy level, check if access token exist in cookie
- if it does not exist request /refresh-token API
- when done /refresh-token request, response to original /profile request.
is there possible way to do this?

**Comment by KoolP** [comment]
Great example thank you @maximilianschmitt 👏  Now the app directory is stable and we will urge for that version 👀
